import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";

const prompt= Prompt({
  subsets: ["thai", "latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});



export const metadata: Metadata = {
  title: "Food Tracker App",
  description: "Generated by create next app",
  keywords: ["Food", "Tracker", "อาหาร", "สุขภาพ","Health"],
  icons: {
    icon: "/vercel.svg",
  },
  authors: [{ 
    name: "Napat Bunyarit",
    url: "https://github.com/s6652410031",
  }],
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={prompt.className}
      >
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
